id: P001799
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:22:20.132499
source_metadata:
  id: bdr:W914
  title: རྒྱུད་སྡེ་སྤྱིའི་རྣམ་བཤད།
  author: ''
  volumes:
    707a4406c424464ebc35f185e196357e:
      image_group_id: I1KG8811
      title: ''
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
