id: P001799
initial_creation_type: ocr
source_metadata:
  id: bdr:W914
  title: རྒྱུད་སྡེ་སྤྱིའི་རྣམ་བཤད།
  author: ''
  volumes:
    707a4406c424464ebc35f185e196357e:
      image_group_id: I1KG8811
      title: ''
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
