id: I40D4E7DE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T22:10:40+00:00'
last_modified: '2022-06-07T15:12:09.632327+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W914
  title: རྒྱུད་སྡེ་སྤྱིའི་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '2496':
      image_group_id: I1KG8811
      title: ''
      total_pages: 130
      order: 1
      base_file: 2496.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
